# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
  - test

# Jobs 

install_dependencies:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

e2etest:    
    stage: test
    before_script:
      - npm install -g http-server
      - npm install cypress@5.3.0
    script:
       # start the server in the background
      - npm run start:ci
      
variables:
 npm_config_cache: "$CI_PROJECT_DIR/.npm"
 CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
 CYPRESS_TMDB_KEY: "82daa40f5828cda045eb76fd2fcb0cdb"